# Generated by Django 5.2.3 on 2025-06-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("project_owner", "Project Owner"),
                    ("project_manager", "Project Manager"),
                    ("developer", "Developer"),
                    ("tester", "Tester"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
